version: '3'
services:
  web:
    build: ./
    ports:
      - '8888:80'
    expose:
      - "80"
      - "9000"
    volumes:
      - ./:/var/www/html/
    links:
      - mysql

  mysql:
    image: mysql:5.7
    container_name: 'yii2-mysql'
    restart: 'always'
    ports:
      - "${DB_PORT}:3306"
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./config/:/docker-entrypoint-initdb.d/

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: 'yii2-phpmyadmin'
    links:
      - mysql
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=${DB_PORT}
    ports:
      - '8080:80'
    volumes:
      - /sessions
