version: '3'

services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - USER=${USER}
    environment:
      - USER=${USER}
    ports:
      - ${WEB_PORT:-8888}:80
    expose:
      - 9000
    volumes:
      - ./:/var/www/html/
    links:
      - mysql

  mysql:
    image: mysql:5.7
    container_name: yii2-mysql
    restart: always
    ports:
      - ${DB_PORT:-3306}:3306
    environment:
      MYSQL_DATABASE: ${DB_NAME:-yii2}
      MYSQL_USER: ${DB_USERNAME:-yii2}
      MYSQL_PASSWORD: ${DB_PASSWORD:-yii2}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-yii2}
    volumes:
      - ./config/:/docker-entrypoint-initdb.d/

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: yii2-phpmyadmin
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: ${DB_PORT:-3306}:3306
    ports:
      - ${PHPMA_PORT:-8080}:80
    volumes:
      - /sessions
